# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 docker-agentpool

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
     
      curl -u $(username):$(password) http://172.22.223.52:8080/job/sonar_deploy/build?token=sonar
